# Generated by Django 3.2.12 on 2022-08-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_coach',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
