# Generated by Django 3.2.12 on 2022-08-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_alter_member_coach_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_coach',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
