# Generated by Django 3.2.12 on 2022-08-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('트레이너', '트레이너'), ('일반유저', '일반 유저')], default=1, max_length=10),
        ),
    ]
