# Generated by Django 3.2.12 on 2022-08-10 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('password', models.IntegerField(null=True)),
                ('category', models.IntegerField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('max_user', models.IntegerField(default=6)),
                ('thumnail', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GX.conference')),
            ],
        ),
    ]
