# Generated by Django 3.2.12 on 2022-08-10 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GX', '0002_user_conference_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_conference',
            name='conference_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entering_room', to='GX.conference'),
        ),
    ]
