# Generated by Django 3.2.12 on 2022-08-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GX', '0002_conference_participates'),
        ('GX', '0002_user_conference_user_id'),
    ]

    operations = [
    ]
