# Generated by Django 3.2.12 on 2022-08-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GX', '0003_merge_20220809_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='Participates',
        ),
    ]
