# Generated by Django 3.2.12 on 2022-08-08 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weight',
            old_name='users',
            new_name='user',
        ),
    ]
